#目录索引
SUP_WAYDORID_INSTALLER_LIB_HOME_PATH=".."
WAYDROID_INSTALLER_LIB_HOME_PATH="."

#文件索引
WAYDROID_INSTALLER_PART1_SH_FILE_PATH="waydroid_installer_part1.sh"
WAYDROID_INSTALLER_PART2_SH_FILE_PATH="waydroid_installer_part2.sh"