#目录索引
SUP_INITIALIZE_TOOLKIT_HOME_PATH=".."
INITIALIZE_TOOLKIT_HOME_PATH="."

#文件索引
CHINESEIZATION_SH_FILE_PATH="$INITIALIZE_TOOLKIT_HOME_PATH/chinesization.sh"
INIT_GIT_SH_FILE_PATH="$INITIALIZE_TOOLKIT_HOME_PATH/init_git.sh"