#目录索引
SUP_WAYDROID_INSTALLER_HOME_PATH=".."
WAYDROID_INSTALLER_HOME_PATH="."

#文件索引
INSTALLER_SH_PATH="$WAYDORID_INSTALLER_HOME_PATH/installer.sh"
WAYDROID_INSTALLER_LIB_PATH="$WAYDROID_INSTALLER_HOME_PATH/index.sh"