#目录索引
SUP_BACKUP_AND_RESOTRE_HOME_PATH=".."
BACKUP_AND_RESTORE_HOME_PATH="."

#文件索引
BACKUP_SH_FILE_PATH="$BACKUP_AND_RESOTRE_HOME_PATH/backup.sh"
RESTORE_SH_FILE_PATH="$BACKUP_AND_RESOTRE_HOME_PATH/restore.sh"