#目录索引
SUP_LINUX_CONFIGURER_HOME_PATH=".."
LINUX_CONFIGURER_HOME_PATH="."

#文件索引
KERNEL_CLEANER_FOLDER_PATH="$LINUX_CONFIGURER_HOME_PATH/kernel_cleaner/index.sh"
NVIDIA_DRIVER_INSTALLLER_FOLDER_PATH="$LINUX_CONFIGURER_HOME_PATH/nvidia_driver_installer/index.sh"